### PR TITLE
[FIX] Fix footer on mobile devices

### PR DESCRIPTION
**Pull request by RahalBhupathi**
Footer should now center on mobile devices (under 600px) and scale the font size according to the view window. Added a media query in footer.module.scss to change the layout of the footer on small screens and adjust the font size. Additionally, I added a Sass mixin to apply different styles based on the screen size, which currently has three size ranges; "small", "medium", and "large". This should be able to be used to scale other elements in the future. Closes issue #20.

Desktop View:
image
Mobile View:
image

### CODE REVIEW

**Comment by yashchaudhari008** [comment]
Can you remove "|" while in mobile view?

**Comment by RahalBhupathi** [comment]
I removed the '|' only for the mobile view
image

**Comment by yashchaudhari008** [comment]
> I removed the '|' only for the mobile view image

The icon should be on the next line, refer the [image on the issue](https://private-user-images.githubusercontent.com/29065088/301841658-be21c4ab-3ea1-4e8b-b8e5-7b079ff464a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjkzOTUsIm5iZiI6MTcxMTEyOTA5NSwicGF0aCI6Ii8yOTA2NTA4OC8zMDE4NDE2NTgtYmUyMWM0YWItM2VhMS00ZThiLWI4ZTUtN2IwNzlmZjQ2NGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE3MzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NTk2NmIxMzkzZDZlY2FkNzRmMzA4ZTE2NWZlYmViMjlhOTIxNDEwMGJmOTQ3NDFlNTVmMjI4MmViYWUzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9M6lLC16WWr0Y4BXkwFEgP0oiK4eTJ-6zPwiY6x80x8)

**Comment by RahalBhupathi** [comment]
I wrapped all the github stuff in a container to ensure they will always be displayed on the same line
image

**Review by yashchaudhari008 — APPROVED** [review]

**Pull request merged**
